# Site settings
title: Dayton Tech Events
email: catherine.devlin@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  An aggregator for information on events (meetings, conferences,
  trainings, etc.) for techies in the Dayton area.
  Yes, it's a plain Jekyll site.  Want to donate a theme?
baseurl: "/dayton-tech-events/" # the subpath of your site, e.g. /blog/
url: "http://dayton-dynamic.github.io" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  catherinedevlin

# Build settings
markdown: kramdown
